name: earthquake_alert
description: Türkiye Deprem Bildirim ve Bilgilendirme Uygulaması
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Network
  http: ^1.1.0
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # UI Components
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  shimmer: ^3.0.0
  
  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.2.2
  connectivity_plus: ^5.0.2
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700